# Generated by Django 5.2 on 2025-08-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id_alter_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quiere_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AddField(
            model_name='order',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='order',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='order',
            name='uso_cfdi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uso CFDI'),
        ),
    ]
