# Generated by Django 5.2 on 2025-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_quiere_factura_order_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rfc',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='RFC'),
        ),
    ]
