# Generated by Django 5.2 on 2025-08-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_calle_order_ciudad_order_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
